# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'musicminutes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for musicminutes
  pod 'Google-Mobile-Ads-SDK'
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'RNIap', :path => '../node_modules/react-native-iap'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  target 'musicminutes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RNSound', :path => '../node_modules/react-native-sound'

  end

  target 'musicminutesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'musicminutes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for musicminutes-tvOS
end
